from time import sleep

raise RuntimeError("An exception occured")
